### ISSUE TITLE
Places list description 

### ISSUE THREAD

**Issue by sms-34** [sfu-dhil/new-narratives#66]
### Describe the feature

- The description of the places list search tab is not clear. What does it mean? It is not clear what these places are: publication of manuscripts, birthplaces of authors, etc..?
- We noticed that the number of places is much less than the number of entries in the database, why? 

URL: https://dhil.lib.sfu.ca/newn/place/

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

All users

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

No alternatives

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

Simplifying the search process for all users.

**Comment by ubermichael** [comment]
A place is a geographic location. It can be a birth place, death place, or publication place. The number of places in the database is less than the number of records because some places are reused and not all entries have places associated with them.

Consider Paris, for example https://dhil.lib.sfu.ca/newn/place/5 - it has multiple records associated with it.
